# -*- coding: utf-8 -*-
"""titanic_deploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srjzhrFVJFrotlFTeIJ34l95LA5H97_h
"""

import streamlit
import joblib as jb
import pandas as pd
import numpy as np


model = jb.load("dt_model.pkl")

st.title("Titanc project 🚢")
st.write("ادخل بيانات الراكب لمعرفه هل كان هينجو ام لا ")

pclass = st.selectbox("passenger class (Pclass)" , [1,2,3])
sex = st.selectbox("sex (Sex)" , ["male" , "female"])
embarked = st.selectbox("Embarked" , ["S", "C" , "Q"])

age = st.number_input("Age" , min_value = 0 , max_value = 100)
sibsp = st.number_input("SibSp" , min_value = 0 , max_value = 10)
parch = st.number_input("parents/children" , min_value = 0 , max_value = 10)
fare = st.number_input("fare" , min_value = 0 )

if st.button("توقع النجاه"):
  input = {"Pclass" : pclass ,
           "Sex" : sex ,
           "Age" : age ,
           "SibSp" : sibsp ,
           "Parch" : parch ,
           "Fare" : fare ,
           "Embarked" : embarked ,
           }
  input_df = pd.DataFrame(input)
  input_df.replace({'Sex':{'male':0,'female':1}, 'Embarked':{'S':0,'C':1,'Q':2}}, inplace=True)

  output = model.predict(input_df)

  if output[0] == 1 :
    st.success("الراكب نجا")
  else :
    st.write("الراكب لم ينجو ❌")
